{
  parserClass="com.github.guillaumetaffin.intellij.ligo.language.jsligo.parser.JsLigoParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="JsLigo"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.guillaumetaffin.intellij.ligo.language.jsligo.psi"
  psiImplPackage="com.github.guillaumetaffin.intellij.ligo.language.jsligo.psi.impl"

  elementTypeHolderClass="com.github.guillaumetaffin.intellij.ligo.language.jsligo.psi.JsLigoTypes"
  elementTypeClass="com.github.guillaumetaffin.intellij.ligo.language.jsligo.psi.JsLigoElementType"
  tokenTypeClass="com.github.guillaumetaffin.intellij.ligo.language.jsligo.psi.JsLigoTokenType"

}

jsLigoFile ::= top_level_declarations*

private top_level_declarations ::= type_alias_declaration
    | var_assignment

type_alias_declaration ::= TYPE_ALIAS_KW IDENTIFIER EQ IDENTIFIER SEMICOLON?

var_assignment ::= (CONST_KW|LET_KW) IDENTIFIER COLON IDENTIFIER EQ var_value SEMICOLON?

var_value ::= STRING_LITERAL
