{
  parserClass="com.github.guillaumetaffin.intellij.ligo.language.jsligo.parser.JsLigoParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="JsLigo"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.guillaumetaffin.intellij.ligo.language.jsligo.psi"
  psiImplPackage="com.github.guillaumetaffin.intellij.ligo.language.jsligo.psi.impl"

  elementTypeHolderClass="com.github.guillaumetaffin.intellij.ligo.language.jsligo.psi.JsLigoTypes"
  elementTypeClass="com.github.guillaumetaffin.intellij.ligo.language.jsligo.psi.JsLigoElementType"
  tokenTypeClass="com.github.guillaumetaffin.intellij.ligo.language.jsligo.psi.JsLigoTokenType"

  tokens = [
    TYPE_DEF_KEYWORD="type"
    SEMICOLON=";"
    ASSIGNMENT_OPERATOR="="
    TYPE_NAME="regexp:[a-zA-Z][a-zA-Z]+"
    WHITE_SPACE="regexp:\s+"
  ]
}

simpleFile ::= item_*

private item_ ::= (type_assignment)

type_assignment ::= TYPE_DEF_KEYWORD TYPE_NAME WHITESPACE? ASSIGNMENT_OPERATOR TYPE_NAME SEMICOLON
